name: Huckleberry Daily Sync

on:
  schedule:
    # Checks every 30 mins at hours 21, 22, 23, and 00 UTC
    # (4:00 PM, 4:30 PM, ... until 7:30 PM EST)
    - cron: '*/30 21-23,0 * * *'
  workflow_dispatch:

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huckleberry-api

      - name: Run Script
        env:
          HUCKLE_EMAIL: ${{ secrets.HUCKLE_EMAIL }}
          HUCKLE_PASS: ${{ secrets.HUCKLE_PASS }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
        run: python sync_script.py
